# Generated by Django 6.0.3 on 2026-04-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('anunciado', 'Anunciado'), ('pre_venda', 'Pré-Venda'), ('lancado', 'Lançado')], default='anunciado', max_length=20)),
            ],
        ),
    ]
